### ISSUE TITLE
need graphics

### ISSUE THREAD

**Issue by oinkBob** [rosaUNTIER/webKamisado#2]
@crossmeadow pls :heart:

**Comment by xmeadow** [comment]
What kind of graphics? All chess pieces?

**Comment by oinkBob** [comment]
everything you come up with, the chess sprite is good enough imo, no need to redo that.. would be nice to have a small collection of all kinds of simple graphics in 2D like trees, clouds, cars, weapons, ships,..

btw big up for the kamisado towers, they are awesome :+1:

**Comment by oinkBob** [comment]
👍
